### ISSUE TITLE
Gives error when trying to compile with Xcode 7.1

### ISSUE THREAD

**Issue by lemonandlime** [daltoniam/JSONJoy-Swift#29]
JSONJoy.m:76:38: Too many arguments to function call, expected 0, have 2

**Comment by daltoniam** [comment]
based on the .m file, I assume you meant to open this on the objective-c version :smile:. I pushed up a fix over there and released a new tag. Thanks for the report.
